<!DOCTYPE html>
<html lang="ja">
<head>
    <title>microute Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="<?php echo $resolver->path() ?>alternative-client-hints"></script>
</head>
<body style="padding: 2em;font-size: 14px;">
<?php echo $contents ?>
</body>
</html>
