<?php ob_start(); ?>
このページは SSE で3秒間隔でデータを垂れ流します<br>

<div>
    <div style="display: flex;gap: 45px">
        <pre id="message"></pre>
        <pre id="userevent"></pre>
    </div>
    <script>
        var message = document.getElementById('message');
        var userevent = document.getElementById('userevent');
        var evtSource = new EventSource("");
        evtSource.addEventListener("message", function (e) {
            message.textContent += e.data + "\n";
        }, false);
        evtSource.addEventListener("userevent", function (e) {
            userevent.textContent += e.data + "\n";
        }, false);
    </script>
</div>

<?php $contents = ob_get_clean(); ?>
<?php include __DIR__ . '/../layout.phtml'; ?>
